# Generated by Django 5.2.3 on 2025-07-02 17:23

import apps.usuarios.models.perfil
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='img/default_avatar.png', null=True, upload_to=apps.usuarios.models.perfil.avatar_upload_path)),
                ('pontos', models.PositiveIntegerField(default=0)),
                ('partidas_jogadas', models.PositiveIntegerField(default=0)),
                ('vitorias', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfilusuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
