# Generated by Django 5.2.3 on 2025-07-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='tema',
            field=models.CharField(choices=[('claro', 'Claro'), ('escuro', 'Escuro')], default='claro', max_length=10),
        ),
    ]
