# Generated by Django 5.2.3 on 2025-07-03 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_perfilusuario_tema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='tema',
            field=models.CharField(choices=[('light', 'Claro'), ('dark', 'Escuro')], default='light', max_length=10),
        ),
    ]
