# Generated by Django 5.2.3 on 2025-07-02 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome da categoria')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Palavra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=100, unique=True, verbose_name='Texto da palavra')),
                ('idioma', models.CharField(default='coreano', max_length=30, verbose_name='Idioma')),
                ('dificuldade', models.PositiveSmallIntegerField(choices=[(1, 'Fácil'), (2, 'Médio'), (3, 'Difícil')], default=1, verbose_name='Dificuldade')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='palavras', to='jogo.categoria')),
            ],
            options={
                'verbose_name': 'Palavra',
                'verbose_name_plural': 'Palavras',
                'ordering': ['texto'],
            },
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tentativas_restantes', models.PositiveSmallIntegerField(default=6, verbose_name='Tentativas restantes')),
                ('letras_tentadas', models.CharField(blank=True, default='', max_length=50, verbose_name='Letras tentadas')),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('vitoria', 'Vitória'), ('derrota', 'Derrota'), ('cancelada', 'Cancelada')], default='em_andamento', max_length=20, verbose_name='Status')),
                ('pontuacao', models.PositiveIntegerField(default=0, verbose_name='Pontuação obtida')),
                ('data_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Início')),
                ('data_fim', models.DateTimeField(blank=True, null=True, verbose_name='Fim')),
                ('palavra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidas', to='jogo.palavra')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
