# Generated by Django 5.2.3 on 2025-07-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='palavra',
            name='jamo',
            field=models.CharField(default=1, max_length=200, verbose_name='Sequência de letras (jamo)'),
            preserve_default=False,
        ),
    ]
