# Generated by Django 5.2.3 on 2025-07-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogo', '0002_palavra_jamo'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='tipo_entrada',
            field=models.CharField(choices=[('digitacao', 'Digitação'), ('blocos', 'Blocos'), ('teclado', 'Teclado Virtual')], default='digitacao', max_length=20, verbose_name='Tipo de entrada'),
        ),
    ]
