# Generated by Django 5.2.3 on 2025-07-02 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogo', '0003_partida_tipo_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='dificuldade',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Dificuldade'),
        ),
    ]
