# Generated by Django 5.2.3 on 2025-07-02 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jogo', '0004_partida_dificuldade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palavra',
            name='dificuldade',
        ),
    ]
